### ISSUE TITLE
Improving the critical path

### ISSUE THREAD

**Issue by Max-Meldrum** [cda-group/arcon#66]
These are just some notes/thoughts. yeah, some of them are quite obvious.

### Pre-allocate ringbuffer/queue rather than doing heap allocation during execution

We are currently using Crossbeam SegQueue that performs heap allocations during runtime. This may be fine in general purpose applications, but for arcon, we need to avoid doing such on the critical path.

A simple benchmark between 2 threads for 400M msgs.

| Queue       |  Throughput  | Type
| ------------- |-------------| ---|
| Crossbeam SegQueue   | 17M | Dynamic |
| Crossbeam ArrayQueue | 35M | Pre-allocated

### Single-writer channels to avoid cache invalidations
The most common channel strategy is a forward one, that is, one-to-one. Therefore, it might make sense to default to SPSC communication between threads/components. 
This would also make it easier to control the flow of watermarks/epochs. If a watermark is signaled on one channel, we simply switch to the other(s) where we expect watermarks.
This would most likely make it faster for downstream event-time triggers to happen and also we avoid having to buffer msgs internally in the component as we can select channels.

| Queue       |  Throughput  | Type
| ------------- |-------------| ---|
| Crossbeam SegQueue (MPMC) | 17M | Dynamic |
| Crossbeam ArrayQueue (MPMC) | 35M | Pre-allocated |
| bounded-spsc-queue | 61M | Pre-allocated |

### Core pinning and NUMA aware placement

Placement matters! For all the results seen so far, the writer and reader have been pinned in such a way that maximised performance.

The following is the layout of my reliable laptop:

![cpu_layout](https://user-images.githubusercontent.com/11488530/72805444-2e012300-3c53-11ea-96b2-c9b7c8e28fb0.png)

| Queue       |  Throughput  | Type | Writer | Reader
| ------------- |-------------| ---| ---| ---|
| Crossbeam SegQueue   | 17M | Dynamic | vcore-0 | vcore-1 |
| Crossbeam SegQueue   | ~17M | Dynamic | vcore-0 | vcore-2 |
| Crossbeam ArrayQueue | 35M | Pre-allocated | vcore-0 | vcore-1 |
| Crossbeam ArrayQueue | 20M | Pre-allocated | vcore-0 | vcore-2 |
| bounded-spsc-queue | 61M | Pre-allocated | vcore-0 | vcore-1 | 
| bounded-spsc-queue | 17M | Pre-allocated | vcore-0 | vcore-2 | 

Also, it might be worth looking into NUMA-aware placements.

### Adaptive buffering of stream elements for improved throughput

Ideally, we would like to avoid popping of element by element. We don't want to spend most of our time in the pop() function and possibly become CPU-bound. Should use some of that memory bandwidth as well.

Suggestion is to buffer elements and read them as batched slices and iterate over them in a loop.

**Comment by Bathtor** [comment]
> The most common channel strategy is a forward one, that is, one-to-one.

I don't think this will be true. Most of the code with this pattern should be fused by the compiler. The most common actual channel implementation should be multiple many-to-one channels, which are encountered during partitioning. So I don't think it's worth optimising for this.

Fixed sized queues are probably a good idea, but we need to integrate that with Adam's work on backpressure, because it would introduce a hard limit on outstanding jobs, the violation of which would cause runtime failures. The SeqQueues may do some allocation, but once they are warmed up and driven at similar load for a while, they usually perform very well...and they do respond to changing load levels, as opposed to ArrayQueues, where you need to pre-allocate for the the worst-case load level in advance.

in the end, in a distributed system usually network traffic will be the bottleneck, not local queues, so prematurely optimising for it is probably not a good way to spend our time.

I do think NUMA aware place is valuable, though. For many jobs this will kind of happen automatically the way that my scheduler is designed, but if we know a fairly static layout a-priori, we could optimise and do slightly more static assignments from the start.

**Comment by Max-Meldrum** [comment]
elements are batched now. NUMA can be looked at through another issue in the future.
